import { dummyPatients } from '../data/dummyPatients';
export const STORAGE_KEY = 'radcare_nusantara_demo_data';
export type PatientStatus = 'Stabil' | 'Perlu Evaluasi' | 'Efek Samping' | 'Selesai';
export type RiskLevel = 'Rendah' | 'Sedang' | 'Tinggi';
export type ScheduleStatus = 'Terjadwal' | 'Berlangsung' | 'Selesai' | 'Ditunda';
export interface DemoPatient { id:string; name:string; age:number; gender:string; diagnosis:string; cancerType:string; stadium:string; plannedSessions:number; completedSessions:number; startDate:string; doctor:string; status:PatientStatus; riskLevel:RiskLevel }
export interface MonitoringNote { id:string; patientId:string; date:string; symptoms:string; severity:'Ringan'|'Sedang'|'Berat'; note:string; riskLevel:RiskLevel }
export interface DoctorNote { id:string; patientId:string; date:string; title:string; content:string; recommendation:string; followUp:boolean }
export interface ScheduleItem { id:string; patientId:string; date:string; time:string; machine:string; status:ScheduleStatus }
export interface AuditLog { id:string; at:string; action:string; detail:string }
export interface DemoSettings { facilityName:string; doctorName:string; location:string; demoMode:boolean; theme:'System'|'Light'|'Dark' }
export interface RadcareData { patients:DemoPatient[]; monitoringNotes:MonitoringNote[]; doctorNotes:DoctorNote[]; schedules:ScheduleItem[]; auditLogs:AuditLog[]; settings:DemoSettings }
const id=()=>Math.random().toString(36).slice(2,10); const today=()=>new Date().toISOString().slice(0,10);
const seed=():RadcareData=>{const patients=dummyPatients.slice(0,3).map((p,i)=>({id:p.id,name:p.name,age:30+i*7,gender:i%2?'Perempuan':'Laki-laki',diagnosis:p.diagnosis,cancerType:p.diagnosis,stadium:p.stadium,plannedSessions:p.totalFractions,completedSessions:p.currentFraction,startDate:today(),doctor:p.doctor,status:'Stabil' as PatientStatus,riskLevel:'Sedang' as RiskLevel})); return {patients,monitoringNotes:[],doctorNotes:[],schedules:patients.map((p,i)=>({id:id(),patientId:p.id,date:today(),time:`0${8+i}:00`,machine:`LINAC-${i+1}`,status:'Terjadwal' as ScheduleStatus})),auditLogs:[],settings:{facilityName:'RADCARE NUSANTARA',doctorName:'dr. Demo',location:'Jakarta',demoMode:true,theme:'System'}}};
const withAudit=(data:RadcareData,action:string,detail:string)=>{data.auditLogs=[{id:id(),at:new Date().toISOString(),action,detail},...data.auditLogs].slice(0,50)};
export function loadRadcareDemoData(){const raw=localStorage.getItem(STORAGE_KEY); if(!raw){const s=seed(); saveRadcareDemoData(s); return s;} try{return JSON.parse(raw) as RadcareData}catch{const s=seed(); saveRadcareDemoData(s); return s;}}
export function saveRadcareDemoData(data:RadcareData){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));}
export function resetRadcareDemoData(){const d=seed(); withAudit(d,'Reset data demo','seed'); saveRadcareDemoData(d); return d;}
export function addPatient(input:Omit<DemoPatient,'id'|'completedSessions'>){const d=loadRadcareDemoData(); const p={...input,id:id(),completedSessions:0}; d.patients.unshift(p); d.schedules.unshift({id:id(),patientId:p.id,date:p.startDate,time:'09:00',machine:'LINAC-1',status:'Terjadwal'}); withAudit(d,'Tambah pasien',p.name); saveRadcareDemoData(d); return p;}
export function updatePatient(patientId:string,updates:Partial<DemoPatient>){const d=loadRadcareDemoData(); d.patients=d.patients.map(p=>p.id===patientId?{...p,...updates}:p); saveRadcareDemoData(d); return d;}
export function updatePatientStatus(patientId:string,status:PatientStatus){const d=updatePatient(patientId,{status}); withAudit(d,'Ubah status pasien',status); saveRadcareDemoData(d); return d;}
export function updateTreatmentProgress(patientId:string,value:number){const d=loadRadcareDemoData(); d.patients=d.patients.map(p=>p.id!==patientId?p:{...p,completedSessions:Math.max(0,Math.min(p.plannedSessions,p.completedSessions+value)),status:Math.max(0,Math.min(p.plannedSessions,p.completedSessions+value))>=p.plannedSessions?'Selesai':p.status}); withAudit(d,'Update progress terapi',`${patientId}:${value}`); saveRadcareDemoData(d); return d;}
export function addMonitoringNote(patientId:string,note:Omit<MonitoringNote,'id'|'patientId'>){const d=loadRadcareDemoData(); d.monitoringNotes.unshift({id:id(),patientId,...note}); if(note.riskLevel==='Tinggi'){d.patients=d.patients.map(p=>p.id===patientId?{...p,status:'Perlu Evaluasi',riskLevel:'Tinggi'}:p);} withAudit(d,'Tambah monitoring note',patientId); saveRadcareDemoData(d); return d;}
export function addDoctorNote(patientId:string,note:Omit<DoctorNote,'id'|'patientId'>){const d=loadRadcareDemoData(); d.doctorNotes.unshift({id:id(),patientId,...note}); withAudit(d,'Tambah doctor note',patientId); saveRadcareDemoData(d); return d;}
export function updateScheduleStatus(scheduleId:string,status:ScheduleStatus){const d=loadRadcareDemoData(); const sc=d.schedules.find(s=>s.id===scheduleId); if(!sc)return d; const before=sc.status; sc.status=status; if(before!=='Selesai'&&status==='Selesai'){d.patients=d.patients.map(p=>p.id!==sc.patientId?p:{...p,completedSessions:Math.min(p.plannedSessions,p.completedSessions+1),status:Math.min(p.plannedSessions,p.completedSessions+1)>=p.plannedSessions?'Selesai':p.status});} withAudit(d,'Update jadwal',status); saveRadcareDemoData(d); return d;}
export function exportRadcareJSON(){return JSON.stringify(loadRadcareDemoData(),null,2)}
export async function importRadcareJSON(file:File){const data=JSON.parse(await file.text()) as RadcareData; withAudit(data,'Restore data demo','import'); saveRadcareDemoData(data); return data;}
export function exportRadcareCSV(){const d=loadRadcareDemoData(); return [['id','name','status','risk','progress'],...d.patients.map(p=>[p.id,p.name,p.status,p.riskLevel,`${p.completedSessions}/${p.plannedSessions}`])].map(r=>r.join(',')).join('\n')}
