import { useMemo, useState } from 'react';
import { addAuditLog, createRecord, deleteRecord, exportCSV, loadAppData, updateRecord } from '../lib/storage';

export default function MonitoringPage(){
  const [tick,setTick]=useState(0); const [q,setQ]=useState(''); const [sev,setSev]=useState('Semua'); const [risk,setRisk]=useState('Semua'); const [rev,setRev]=useState('Semua');
  const d=loadAppData(); const notes=d.monitoringNotes||[]; const patients=d.patients||[];
  const rows=useMemo(()=>notes.filter((n:any)=>{const p=patients.find((x:any)=>x.id===n.patientId); const name=(n.patientName||p?.name||'').toLowerCase(); return name.includes(q.toLowerCase())&&(sev==='Semua'||n.severity===sev)&&(risk==='Semua'||n.riskLevel===risk)&&(rev==='Semua'||n.reviewStatus===rev)}),[tick,q,sev,risk,rev]);
  const add=()=>{const p=patients[0]; if(!p)return; const item={id:`m_${Date.now()}`,patientId:p.id,patientName:p.name,date:new Date().toISOString().slice(0,10),symptom:'Mual',severity:'Sedang',riskLevel:'Sedang',note:'Monitoring baru',reportedBy:'Perawat Demo',reviewStatus:'Belum Direview',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}; createRecord('monitoringNotes',item); addAuditLog('Tambah monitoring','monitoringNotes',item.id,'Menambah monitoring'); setTick(tick+1)};
  return <div className='space-y-4'><div className='rounded-3xl border bg-white p-5'><h1 className='text-2xl font-bold'>Monitoring Pasien</h1><p className='text-sm text-slate-600'>Pantau efek samping, keluhan, dan risiko pasien radioterapi.</p></div>
  <div className='grid gap-3 md:grid-cols-4'>{[['Total Monitoring',notes.length],['Keluhan Berat',notes.filter((x:any)=>x.severity==='Berat').length],['Risiko Tinggi',notes.filter((x:any)=>x.riskLevel==='Tinggi').length],['Belum Direview',notes.filter((x:any)=>x.reviewStatus==='Belum Direview').length]].map(([k,v])=><div key={String(k)} className='rounded-2xl border bg-white p-4'><p className='text-xs'>{k}</p><p className='text-2xl font-bold'>{v as any}</p></div>)}</div>
  <div className='grid gap-2 md:grid-cols-6'><input className='h-11 rounded-xl border px-3' placeholder='Cari pasien' value={q} onChange={e=>setQ(e.target.value)}/><select className='h-11 rounded-xl border px-3' value={sev} onChange={e=>setSev(e.target.value)}><option>Semua</option><option>Ringan</option><option>Sedang</option><option>Berat</option></select><select className='h-11 rounded-xl border px-3' value={risk} onChange={e=>setRisk(e.target.value)}><option>Semua</option><option>Rendah</option><option>Sedang</option><option>Tinggi</option></select><select className='h-11 rounded-xl border px-3' value={rev} onChange={e=>setRev(e.target.value)}><option>Semua</option><option>Belum Direview</option><option>Perlu Evaluasi</option><option>Sudah Direview</option></select><button className='h-11 rounded-xl bg-blue-600 text-white' onClick={add}>Tambah</button><button className='h-11 rounded-xl bg-slate-900 text-white' onClick={()=>{navigator.clipboard.writeText(exportCSV('monitoringNotes')); addAuditLog('Export laporan','monitoringNotes','-','Export CSV monitoring')}}>Export CSV</button></div>
  <div className='grid gap-3'>{rows.map((n:any)=><div key={n.id} className='rounded-2xl border bg-white p-4'><div className='flex justify-between'><p className='font-semibold'>{n.patientName||patients.find((p:any)=>p.id===n.patientId)?.name}</p><p>{n.severity} • {n.riskLevel}</p></div><p className='text-sm'>{n.note}</p><div className='mt-2 flex gap-2 text-sm'><button onClick={()=>{updateRecord('monitoringNotes',n.id,{reviewStatus:'Sudah Direview'}); addAuditLog('Edit monitoring','monitoringNotes',n.id,'Review monitoring'); setTick(tick+1)}}>Review</button><button className='text-rose-600' onClick={()=>{deleteRecord('monitoringNotes',n.id); addAuditLog('Hapus monitoring','monitoringNotes',n.id,'Hapus monitoring'); setTick(tick+1)}}>Hapus</button></div></div>)}</div></div>
}
